/**
 * signing.ts — HARDEN-2 H-02: producer authenticity for backup manifests.
 *
 * Recipient (age) encryption proves CONFIDENTIALITY, not who wrote the object:
 * anyone with bucket write access could plant a matching artifact+manifest
 * pair. The fix is an Ed25519 signature over the EXACT serialized manifest
 * bytes, made by the backup producer (BACKUP_SIGNING_KEY, cron-service env)
 * and verified by the restore drill (BACKUP_VERIFY_PUBKEY) BEFORE any
 * download-trusting, decryption, or privileged pg_restore.
 *
 * Signing the exact uploaded bytes (not a re-canonicalized object) removes
 * every canonicalization pitfall: the manifest already binds environment,
 * object key, byte lengths, both hashes, schema version, timestamp, source
 * commit, and the migration list — the restore side re-checks those fields
 * AFTER the signature anchors them.
 *
 * The signature travels as a sibling object: `<manifestKey>.sig` (base64).
 * Keys are PEM (PKCS#8 private / SPKI public), generated by `npm run keygen`
 * in this app — the private half belongs in the cron service env + the
 * owner's password manager, NEVER in the repo.
 */
import { createPrivateKey, createPublicKey, sign, verify, type KeyObject } from 'node:crypto';

export const SIGNATURE_SUFFIX = '.sig';

export function signatureKeyFor(manifestKey: string): string {
  return `${manifestKey}${SIGNATURE_SUFFIX}`;
}

function privateKeyFrom(pem: string): KeyObject {
  const key = createPrivateKey(pem);
  if (key.asymmetricKeyType !== 'ed25519') throw new Error(`BACKUP_SIGNING_KEY must be Ed25519 (got ${key.asymmetricKeyType}).`);
  return key;
}

function publicKeyFrom(pem: string): KeyObject {
  const key = createPublicKey(pem);
  if (key.asymmetricKeyType !== 'ed25519') throw new Error(`BACKUP_VERIFY_PUBKEY must be Ed25519 (got ${key.asymmetricKeyType}).`);
  return key;
}

/** Sign the exact manifest bytes; returns base64. */
export function signManifestBytes(serializedManifest: string, privateKeyPem: string): string {
  return sign(null, Buffer.from(serializedManifest, 'utf8'), privateKeyFrom(privateKeyPem)).toString('base64');
}

/**
 * Verify a base64 signature over the exact manifest bytes. A malformed PUBLIC
 * KEY is an operator configuration error and throws loudly; a bad/garbled
 * SIGNATURE is an authenticity failure and returns false.
 */
export function verifyManifestBytes(serializedManifest: string, signatureB64: string, publicKeyPem: string): boolean {
  const key = publicKeyFrom(publicKeyPem); // loud on misconfiguration
  const sig = Buffer.from(signatureB64.trim(), 'base64');
  if (sig.length === 0) return false;
  try {
    return verify(null, Buffer.from(serializedManifest, 'utf8'), key, sig);
  } catch {
    return false;
  }
}

// ── restore-side schema validation (H-02: never JSON.parse-and-trust) ────────
// Hand-rolled (no zod: the backup image ships self-contained by packaging
// contract — see restore-main.ts's import note).

export interface ValidatedLatestSuccess {
  readonly schema: 'c3-backup-latest-success/1';
  readonly lastSuccessUtc: string;
  readonly objectKey: string;
  readonly manifestKey: string;
  readonly environment: string;
  readonly mode: string;
  readonly encryptedSha256: string;
  readonly encryptedBytes: number;
}

export interface ValidatedManifest {
  readonly schema: 'c3-backup-manifest/1';
  readonly environment: string;
  readonly createdAtUtc: string;
  readonly mode: string;
  readonly objectKey: string;
  readonly sourceCommit: string;
  readonly migrations: string[];
  readonly encryptedSha256: string;
  readonly encryptedBytes: number;
  readonly plaintextSha256: string;
  readonly plaintextBytes: number;
}

const SHA256_RE = /^[a-f0-9]{64}$/;

function fail(doc: string, field: string, why: string): never {
  throw new Error(`${doc} failed schema validation: ${field} ${why}.`);
}

function reqString(doc: string, o: Record<string, unknown>, field: string): string {
  const v = o[field];
  if (typeof v !== 'string' || v.length === 0) fail(doc, field, 'must be a non-empty string');
  return v;
}

function reqInt(doc: string, o: Record<string, unknown>, field: string): number {
  const v = o[field];
  if (typeof v !== 'number' || !Number.isInteger(v) || v <= 0) fail(doc, field, 'must be a positive integer');
  return v;
}

function reqSha(doc: string, o: Record<string, unknown>, field: string): string {
  const v = reqString(doc, o, field);
  if (!SHA256_RE.test(v)) fail(doc, field, 'must be a lowercase hex sha256');
  return v;
}

export function validateLatestSuccess(raw: unknown): ValidatedLatestSuccess {
  if (typeof raw !== 'object' || raw === null) fail('latest-success', 'document', 'must be a JSON object');
  const o = raw as Record<string, unknown>;
  if (o.schema !== 'c3-backup-latest-success/1') fail('latest-success', 'schema', 'is not c3-backup-latest-success/1');
  return {
    schema: 'c3-backup-latest-success/1',
    lastSuccessUtc: reqString('latest-success', o, 'lastSuccessUtc'),
    objectKey: reqString('latest-success', o, 'objectKey'),
    manifestKey: reqString('latest-success', o, 'manifestKey'),
    environment: reqString('latest-success', o, 'environment'),
    mode: reqString('latest-success', o, 'mode'),
    encryptedSha256: reqSha('latest-success', o, 'encryptedSha256'),
    encryptedBytes: reqInt('latest-success', o, 'encryptedBytes'),
  };
}

export function validateManifest(raw: unknown): ValidatedManifest {
  if (typeof raw !== 'object' || raw === null) fail('manifest', 'document', 'must be a JSON object');
  const o = raw as Record<string, unknown>;
  if (o.schema !== 'c3-backup-manifest/1') fail('manifest', 'schema', 'is not c3-backup-manifest/1');
  const migrations = o.migrations;
  if (!Array.isArray(migrations) || migrations.some((m) => typeof m !== 'string')) fail('manifest', 'migrations', 'must be a string array');
  return {
    schema: 'c3-backup-manifest/1',
    environment: reqString('manifest', o, 'environment'),
    createdAtUtc: reqString('manifest', o, 'createdAtUtc'),
    mode: reqString('manifest', o, 'mode'),
    objectKey: reqString('manifest', o, 'objectKey'),
    sourceCommit: reqString('manifest', o, 'sourceCommit'),
    migrations: migrations as string[],
    encryptedSha256: reqSha('manifest', o, 'encryptedSha256'),
    encryptedBytes: reqInt('manifest', o, 'encryptedBytes'),
    plaintextSha256: reqSha('manifest', o, 'plaintextSha256'),
    plaintextBytes: reqInt('manifest', o, 'plaintextBytes'),
  };
}

/**
 * The cross-document consistency law: the signed manifest must AGREE with the
 * (unsigned, mutable) latest-success pointer that led us to it. The pointer
 * only routes; the manifest is the authority once its signature verifies.
 */
export function assertMarkerMatchesManifest(latest: ValidatedLatestSuccess, manifest: ValidatedManifest): void {
  if (latest.objectKey !== manifest.objectKey) throw new Error('Marker/manifest disagree on objectKey.');
  if (latest.encryptedSha256 !== manifest.encryptedSha256) throw new Error('Marker/manifest disagree on encryptedSha256.');
  if (latest.encryptedBytes !== manifest.encryptedBytes) throw new Error('Marker/manifest disagree on encryptedBytes.');
  if (latest.environment !== manifest.environment) throw new Error('Marker/manifest disagree on environment.');
}
