/**
 * signing.ts — HARDEN-2 H-02: producer authenticity for backup manifests.
 *
 * Recipient (age) encryption proves CONFIDENTIALITY, not who wrote the object:
 * anyone with bucket write access could plant a matching artifact+manifest
 * pair. The fix is an Ed25519 signature over the EXACT serialized manifest
 * bytes, made by the backup producer (BACKUP_SIGNING_KEY, cron-service env)
 * and verified by the restore drill (BACKUP_VERIFY_PUBKEY) BEFORE any
 * download-trusting, decryption, or privileged pg_restore.
 *
 * Signing the exact uploaded bytes (not a re-canonicalized object) removes
 * every canonicalization pitfall: the manifest already binds environment,
 * object key, byte lengths, both hashes, schema version, timestamp, source
 * commit, and the migration list — the restore side re-checks those fields
 * AFTER the signature anchors them.
 *
 * The signature travels as a sibling object: `<manifestKey>.sig` (base64).
 * Keys are PEM (PKCS#8 private / SPKI public), generated by `npm run keygen`
 * in this app — the private half belongs in the cron service env + the
 * owner's password manager, NEVER in the repo.
 */
import { createPrivateKey, createPublicKey, sign, verify, type KeyObject } from 'node:crypto';

export const SIGNATURE_SUFFIX = '.sig';

export function signatureKeyFor(manifestKey: string): string {
  return `${manifestKey}${SIGNATURE_SUFFIX}`;
}

function privateKeyFrom(pem: string): KeyObject {
  const key = createPrivateKey(pem);
  if (key.asymmetricKeyType !== 'ed25519') throw new Error(`BACKUP_SIGNING_KEY must be Ed25519 (got ${key.asymmetricKeyType}).`);
  return key;
}

function publicKeyFrom(pem: string): KeyObject {
  const key = createPublicKey(pem);
  if (key.asymmetricKeyType !== 'ed25519') throw new Error(`BACKUP_VERIFY_PUBKEY must be Ed25519 (got ${key.asymmetricKeyType}).`);
  return key;
}

/** Sign the exact manifest bytes; returns base64. */
export function signManifestBytes(serializedManifest: string, privateKeyPem: string): string {
  return sign(null, Buffer.from(serializedManifest, 'utf8'), privateKeyFrom(privateKeyPem)).toString('base64');
}

/**
 * Verify a base64 signature over the exact manifest bytes. A malformed PUBLIC
 * KEY is an operator configuration error and throws loudly; a bad/garbled
 * SIGNATURE is an authenticity failure and returns false.
 */
export function verifyManifestBytes(serializedManifest: string, signatureB64: string, publicKeyPem: string): boolean {
  const key = publicKeyFrom(publicKeyPem); // loud on misconfiguration
  const sig = Buffer.from(signatureB64.trim(), 'base64');
  if (sig.length === 0) return false;
  try {
    return verify(null, Buffer.from(serializedManifest, 'utf8'), key, sig);
  } catch {
    return false;
  }
}

/**
 * R2-N07: derive the SPKI public-key PEM from the Ed25519 PRIVATE signing key,
 * so the producer can verify the signature it just wrote when it reads the
 * sidecar back from the store — closing the loop before the success marker.
 */
export function publicKeyPemFromPrivate(privateKeyPem: string): string {
  return createPublicKey(privateKeyFrom(privateKeyPem)).export({ type: 'spki', format: 'pem' }).toString();
}

// ── restore-side schema validation (H-02: never JSON.parse-and-trust) ────────
// Hand-rolled (no zod: the backup image ships self-contained by packaging
// contract — see restore-main.ts's import note).

export interface ValidatedLatestSuccess {
  readonly schema: 'c3-backup-latest-success/1';
  readonly lastSuccessUtc: string;
  readonly objectKey: string;
  readonly manifestKey: string;
  readonly environment: string;
  readonly mode: string;
  readonly encryptedSha256: string;
  readonly encryptedBytes: number;
}

export interface ValidatedBlobClass {
  readonly count: number;
  readonly sample: { readonly storageKey: string; readonly sha256: string } | null;
}
export interface ValidatedBlobInventory {
  readonly document: ValidatedBlobClass;
  readonly photo: ValidatedBlobClass;
  readonly intake: ValidatedBlobClass;
}
export interface ValidatedBlobArchiveEntry {
  readonly storageKey: string;
  readonly sha256: string;
  readonly cls: 'document' | 'photo' | 'intake';
}
export interface ValidatedBlobArchive {
  readonly key: string;
  readonly sha256: string;
  readonly bytes: number;
  readonly entryCount: number;
  readonly entries: ValidatedBlobArchiveEntry[];
}

export interface ValidatedManifest {
  readonly schema: 'c3-backup-manifest/1';
  readonly environment: string;
  readonly createdAtUtc: string;
  readonly mode: string;
  readonly objectKey: string;
  readonly sourceCommit: string;
  readonly migrations: string[];
  readonly encryptedSha256: string;
  readonly encryptedBytes: number;
  readonly plaintextSha256: string;
  readonly plaintextBytes: number;
  /** H-08: the object-store census (recoverability checklist for the drill). */
  readonly blobInventory: ValidatedBlobInventory;
  /** H-08 (Option A): descriptor of the independent encrypted blob snapshot, or
   *  null (no blobs, or a pre-Option-A manifest — the drill decides what null means). */
  readonly blobArchive: ValidatedBlobArchive | null;
}

const SHA256_RE = /^[a-f0-9]{64}$/;

function fail(doc: string, field: string, why: string): never {
  throw new Error(`${doc} failed schema validation: ${field} ${why}.`);
}

function reqString(doc: string, o: Record<string, unknown>, field: string): string {
  const v = o[field];
  if (typeof v !== 'string' || v.length === 0) fail(doc, field, 'must be a non-empty string');
  return v;
}

function reqInt(doc: string, o: Record<string, unknown>, field: string): number {
  const v = o[field];
  if (typeof v !== 'number' || !Number.isInteger(v) || v <= 0) fail(doc, field, 'must be a positive integer');
  return v;
}

function reqSha(doc: string, o: Record<string, unknown>, field: string): string {
  const v = reqString(doc, o, field);
  if (!SHA256_RE.test(v)) fail(doc, field, 'must be a lowercase hex sha256');
  return v;
}

/** H-08: validate one blob class { count>=0, sample: null | {storageKey, sha256} }. */
function reqBlobClass(o: Record<string, unknown>, cls: string): ValidatedBlobClass {
  const field = `blobInventory.${cls}`;
  const v = o[cls];
  if (typeof v !== 'object' || v === null) fail('manifest', field, 'must be an object');
  const c = v as Record<string, unknown>;
  const count = c.count;
  if (typeof count !== 'number' || !Number.isInteger(count) || count < 0) fail('manifest', `${field}.count`, 'must be a non-negative integer');
  const s = c.sample;
  if (s === null) return { count, sample: null };
  if (typeof s !== 'object') fail('manifest', `${field}.sample`, 'must be null or an object');
  const so = s as Record<string, unknown>;
  const storageKey = so.storageKey;
  const sha256 = so.sha256;
  if (typeof storageKey !== 'string' || storageKey.length === 0) fail('manifest', `${field}.sample.storageKey`, 'must be a non-empty string');
  if (typeof sha256 !== 'string' || !SHA256_RE.test(sha256)) fail('manifest', `${field}.sample.sha256`, 'must be a lowercase hex sha256');
  if (count === 0) fail('manifest', `${field}`, 'has a sample but count 0 (inconsistent)');
  return { count, sample: { storageKey, sha256 } };
}

const EMPTY_BLOB_INVENTORY: ValidatedBlobInventory = {
  document: { count: 0, sample: null },
  photo: { count: 0, sample: null },
  intake: { count: 0, sample: null },
};

function optBlobInventory(o: Record<string, unknown>): ValidatedBlobInventory {
  // Backward-compatible: a pre-H-08 manifest has no census. Treat it as empty
  // (the drill then has no objects to prove) rather than failing the restore of
  // a legacy backup. A PRESENT inventory is validated strictly.
  const v = o.blobInventory;
  if (v === undefined) return EMPTY_BLOB_INVENTORY;
  if (typeof v !== 'object' || v === null) fail('manifest', 'blobInventory', 'must be an object');
  const inv = v as Record<string, unknown>;
  return {
    document: reqBlobClass(inv, 'document'),
    photo: reqBlobClass(inv, 'photo'),
    intake: reqBlobClass(inv, 'intake'),
  };
}

function optBlobArchive(o: Record<string, unknown>): ValidatedBlobArchive | null {
  // Absent/null → no independent copy (pre-Option-A, or a zero-blob tenant). The
  // drill decides whether that is acceptable (it fails if the inventory has
  // objects). A PRESENT archive is validated strictly.
  const v = o.blobArchive;
  if (v === undefined || v === null) return null;
  if (typeof v !== 'object') fail('manifest', 'blobArchive', 'must be an object or null');
  const a = v as Record<string, unknown>;
  const key = a.key;
  if (typeof key !== 'string' || key.length === 0) fail('manifest', 'blobArchive.key', 'must be a non-empty string');
  const sha256 = a.sha256;
  if (typeof sha256 !== 'string' || !SHA256_RE.test(sha256)) fail('manifest', 'blobArchive.sha256', 'must be a lowercase hex sha256');
  const bytes = a.bytes;
  if (typeof bytes !== 'number' || !Number.isInteger(bytes) || bytes <= 0) fail('manifest', 'blobArchive.bytes', 'must be a positive integer');
  const rawEntries = a.entries;
  if (!Array.isArray(rawEntries) || rawEntries.length === 0) fail('manifest', 'blobArchive.entries', 'must be a non-empty array');
  const entries: ValidatedBlobArchiveEntry[] = rawEntries.map((e, i) => {
    if (typeof e !== 'object' || e === null) fail('manifest', `blobArchive.entries[${i}]`, 'must be an object');
    const eo = e as Record<string, unknown>;
    if (typeof eo.storageKey !== 'string' || eo.storageKey.length === 0) fail('manifest', `blobArchive.entries[${i}].storageKey`, 'must be a non-empty string');
    if (typeof eo.sha256 !== 'string' || !SHA256_RE.test(eo.sha256)) fail('manifest', `blobArchive.entries[${i}].sha256`, 'must be a lowercase hex sha256');
    if (eo.cls !== 'document' && eo.cls !== 'photo' && eo.cls !== 'intake') fail('manifest', `blobArchive.entries[${i}].cls`, 'must be document|photo|intake');
    return { storageKey: eo.storageKey, sha256: eo.sha256, cls: eo.cls };
  });
  const entryCount = a.entryCount;
  if (entryCount !== entries.length) fail('manifest', 'blobArchive.entryCount', 'must equal entries.length');
  return { key, sha256, bytes, entryCount, entries };
}

export function validateLatestSuccess(raw: unknown): ValidatedLatestSuccess {
  if (typeof raw !== 'object' || raw === null) fail('latest-success', 'document', 'must be a JSON object');
  const o = raw as Record<string, unknown>;
  if (o.schema !== 'c3-backup-latest-success/1') fail('latest-success', 'schema', 'is not c3-backup-latest-success/1');
  return {
    schema: 'c3-backup-latest-success/1',
    lastSuccessUtc: reqString('latest-success', o, 'lastSuccessUtc'),
    objectKey: reqString('latest-success', o, 'objectKey'),
    manifestKey: reqString('latest-success', o, 'manifestKey'),
    environment: reqString('latest-success', o, 'environment'),
    mode: reqString('latest-success', o, 'mode'),
    encryptedSha256: reqSha('latest-success', o, 'encryptedSha256'),
    encryptedBytes: reqInt('latest-success', o, 'encryptedBytes'),
  };
}

export function validateManifest(raw: unknown): ValidatedManifest {
  if (typeof raw !== 'object' || raw === null) fail('manifest', 'document', 'must be a JSON object');
  const o = raw as Record<string, unknown>;
  if (o.schema !== 'c3-backup-manifest/1') fail('manifest', 'schema', 'is not c3-backup-manifest/1');
  const migrations = o.migrations;
  if (!Array.isArray(migrations) || migrations.some((m) => typeof m !== 'string')) fail('manifest', 'migrations', 'must be a string array');
  return {
    schema: 'c3-backup-manifest/1',
    environment: reqString('manifest', o, 'environment'),
    createdAtUtc: reqString('manifest', o, 'createdAtUtc'),
    mode: reqString('manifest', o, 'mode'),
    objectKey: reqString('manifest', o, 'objectKey'),
    sourceCommit: reqString('manifest', o, 'sourceCommit'),
    migrations: migrations as string[],
    encryptedSha256: reqSha('manifest', o, 'encryptedSha256'),
    encryptedBytes: reqInt('manifest', o, 'encryptedBytes'),
    plaintextSha256: reqSha('manifest', o, 'plaintextSha256'),
    plaintextBytes: reqInt('manifest', o, 'plaintextBytes'),
    blobInventory: optBlobInventory(o),
    blobArchive: optBlobArchive(o),
  };
}

/**
 * The cross-document consistency law: the signed manifest must AGREE with the
 * (unsigned, mutable) latest-success pointer that led us to it. The pointer
 * only routes; the manifest is the authority once its signature verifies.
 */
export function assertMarkerMatchesManifest(latest: ValidatedLatestSuccess, manifest: ValidatedManifest): void {
  if (latest.objectKey !== manifest.objectKey) throw new Error('Marker/manifest disagree on objectKey.');
  if (latest.encryptedSha256 !== manifest.encryptedSha256) throw new Error('Marker/manifest disagree on encryptedSha256.');
  if (latest.encryptedBytes !== manifest.encryptedBytes) throw new Error('Marker/manifest disagree on encryptedBytes.');
  if (latest.environment !== manifest.environment) throw new Error('Marker/manifest disagree on environment.');
}
