/**
 * bankForm.ts — S12: the bank beneficiary-registration XLSX, generated from
 * the registry with the SENSITIVE COLUMNS BLANK.
 *
 * THE STANDING LAW (owner, absolute): account numbers, IBANs and card numbers
 * never enter C3 — not in the database, not in this generator's inputs. The
 * form carries everything the registry lawfully knows (person, label, bank,
 * country, currency, payment type, org entity) and leaves Account Number /
 * IBAN / SWIFT-BIC as EMPTY columns to be completed by hand outside C3.
 * Losing a filled form means asking the person again (plan open-question 5
 * default: the law stands; no transient-storage ceremony without an explicit
 * owner decision).
 */
import ExcelJS from 'exceljs';
import type { Beneficiary } from '@c3web/domain';

export async function buildBankRegistrationForm(personName: string, rows: readonly Beneficiary[]): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'C3';
  const ws = wb.addWorksheet('Beneficiary Registration');

  ws.addRow([`Beneficiary registration — ${personName}`]);
  ws.addRow([`Generated by C3 on ${new Date().toISOString().slice(0, 10)} — sensitive columns are intentionally blank; complete them by hand.`]);
  ws.addRow([]);

  const header = [
    'Beneficiary Name',
    'Label',
    'Bank Name',
    'Bank Country',
    'Currency',
    'Payment Type',
    'Registered With (C3 Entity)',
    'Status',
    // ── the lawful blanks ──
    'Account Number (fill by hand)',
    'IBAN (fill by hand)',
    'SWIFT / BIC (fill by hand)',
  ];
  const headerRow = ws.addRow(header);
  headerRow.font = { bold: true };

  for (const b of rows.filter((x) => x.status !== 'Retired')) {
    ws.addRow([personName, b.label, b.bankName, b.bankCountry, b.currency, b.paymentType ?? '', b.registeredWithEntityId ?? '', b.status, '', '', '']);
  }

  ws.columns.forEach((col) => {
    let max = 12;
    col.eachCell?.({ includeEmpty: false }, (cell) => {
      max = Math.max(max, String(cell.value ?? '').length + 2);
    });
    col.width = Math.min(max, 44);
  });

  const out = await wb.xlsx.writeBuffer();
  return Buffer.from(out as ArrayBuffer);
}
